# Generated by Django 6.1.1 on 2026-09-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
    ]
